- README.md
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
I had a problem with a project where root gradle dir is not the same as git repo root. This should fix it.
> Added gitRepositoryRoot property to override git repo root location

- build.gradle
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
Set task.inputs.dir to .git directory and set task.output.file to git.properties file.  Gradle can then check if input and output are already set up.  If so, task is not executed.
> Set inputs and outputs for up-to-date check

- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
I experienced a NPE when running the build without settings _keys_ variable in my build.gradle. _project.gitProperties.keys_ is null, _keys_ which has sensible defaults is not used.
> Fixed NPE. Occured when git properties are not set in build.gradle

- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
Ensure JavaPlugin is applied to project before referencing task defined in JavaPlugin.
> Fixes https://github.com/n0mer/gradle-git-properties/issues/5

- README.md
- build.gradle
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
Added two new configuration keys dateFormat and dateFormatTimeZone to allow formatting git.commit.time
> Adding format support for the date in git.commit.time (Issue #13)

- build.gradle
This will make it possible to use the plugin in builds that for some reason have to run on Java 7.
Fixes issue #21
> Set targetCompatibility to Java 7

- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
- src/test/groovy/com/gorylenko/GitPropertiesPluginTests.groovy
When a repository is not in a completely clean state, the Maven `git-commit-id-plugin`plugin sets `git.dirty=true`. This is helpful to know whether a build can be reproduced from a given commit.
> Add git.dirty property (same as maven plugin)

- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
- src/test/groovy/com/gorylenko/GitPropertiesPluginTests.groovy
Mimic the behavior `git-commit-id-plugin` for `git-describe` (issue #31).
> Add git.commit.id.describe property (similar to maven plugin)

- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
when reading the git.properties file, Spring uses the method java.util.Properties.load(InputStream inStream).
This method expects an InputStream with ISO-8859-1 encoding.
gradle-git-properties however stores the git.properties file with UTF-8 encoding. This will, for instance with german commit messages containing charachters like ä, ö, ü or ß, cause messed up strings.
The git.properties file should thus be written with ISO-8859-1 encoding.
> change encoding of git.properties to ISO-8859-1

- README.md
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
- src/test/groovy/com/gorylenko/GitPropertiesPluginTests.groovy
The previous PR #47 (for issue #46) requires users to specify git branch name manually while the issue #46 clearly mentioned that the value should be detected automatically from system environment variables (like maven-git-commit-id-plugin). This PR is to replace PR #47 and make this plugin to be consistent to maven-git-commit-id plugin.
> Fix #26 (Allow branch name to be overridden using env vars)

- README.md
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
Fix issue #54 and issue #55. 
Only initialize properties will be used.
Support adding custom properties (expressions and closures). Closures can access Grgit object via **it** variable.
> Fix #55 (Support adding custom properties)

- README.md
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
Fix issue #57 (All properties are generated when configuring gitProperties { keys = [] })
Also remove the redundant key KEY_GIT_COMMIT_TIME in KEY_ALL
> Fix issue #57 (All properties are generated when keys=[])

- src/main/groovy/com/gorylenko/GitDirLocator.groovy
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
Fix issue #23 by adding logic from maven-git-commit-id plugin to lookup for .git directory (which also add supports git modules)
> Fix issue #23 (Support git modules)

- build.gradle
Now the plugin requires Java 8 since 9b8fb3363ebf740aba64459c767e5aa3add8aab1
> Upgrade target compatibility to Java 8

- build.gradle
I am updating the `grgit-core` dependency to `4.1.0` to avoid the "`close() called when useCnt is already zero for Repository[......./.git]`" warning when the task `generateGitProperties` is called.
---
See ajoberstar/grgit#305
> Update grgit-core to 4.1.0

- src/main/groovy/com/gorylenko/GenerateGitPropertiesTask.groovy
- src/test/groovy/com/gorylenko/GitPropertiesPluginTests.groovy
`GitPropertiesPluginTests#testGenerateWithMissingGitRepoShouldFail` incorrectly asserted that every exception would be a `RepositoryNotFoundException` while in reality the thrown exception was about `Assert.fail()` not being imported and no such method could be found.
While fixing the test, I learned that JGit wouldn't throw a `RepositoryNotFoundException` in every case but happily walk up the directory tree until it found a `.git` directory starting from the current working directory with `findGitDir()` (see [`BaseRepositoryBuilder#findGitDir()`](https://archive.eclipse.org/jgit/site/3.7.0.201502260915-r/org.eclipse.jgit/apidocs/org/eclipse/jgit/lib/BaseRepositoryBuilder.html#findGitDir()), [`BaseRepositoryBuilder#findGitDir(java.io.File)`](https://archive.eclipse.org/jgit/site/3.7.0.2015 …
> Throw GradleException if .git directory is missing

- build.gradle
Replace JCenter with Maven Central and the static repository of @ajoberstar.
Closes #166
> Remove dependency on JCenter due to its shutdown

- README.md
- build.gradle
- src/main/groovy/com/gorylenko/GenerateGitPropertiesTask.groovy
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
- src/test/groovy/com/gorylenko/BackwardCompatibilityFunctionalTest.groovy
- src/test/groovy/com/gorylenko/BasicFunctionalTest.groovy
- src/test/groovy/com/gorylenko/BuildCacheFunctionalTest.groovy
- src/test/groovy/com/gorylenko/ConfigurationCacheFunctionalTest.groovy
- src/test/groovy/com/gorylenko/GitPropertiesPluginTests.groovy
Remove problematic invocations in the task action and replace them with the recommended replacements from the Gradle documentation.
https://docs.gradle.org/6.8.3/userguide/configuration_cache.html
https://docs.gradle.org/6.8.3/userguide/lazy_configuration.html
Closes #160
> Add support for configuration cache

- src/main/groovy/com/gorylenko/GenerateGitPropertiesTask.groovy
- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
- src/test/groovy/com/gorylenko/BackwardCompatibilityFunctionalTest.groovy
- src/test/groovy/com/gorylenko/BuildSrcFunctionalTest.groovy
The changes in #164 to support the Gradle configuration cache broke using the plugin during the configuration phase of Gradle (e. g. as part of a custom plugin via `buildSrc` and similar use cases).
Instead of relying on [`Gradle#projectsEvaluated()`](https://docs.gradle.org/6.8.3/javadoc/org/gradle/api/invocation/Gradle.html#projectsEvaluated-groovy.lang.Closure-) which isn't available during the configuration phase to add additional resource directories to the `main` source set, the plugin now lazily modifies the main source set.
Fixes #169
> Make plugin work during configuration phase again

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
After OpenJDK 16 was disabled in #165 because the plugin was incompatible at that time, it should now work with Gradle 7.0 and Java 16.
Refs #173
> Add Java 16 to Travis CI and upgrade to Gradle 7.0

- README.md
- build.gradle
Fix #195
We've used grgit v4.1.0 since 76a0f0aaa20317cd7e694f244080e1c7b4a74c5a, which included in v2.2.4 to v2.3.1.
Reference for grgit v4.1.1: ajoberstar/grgit#339
> Update grgit-core to 4.1.1 (Fix #195)

- build.gradle
- src/integrationTest/groovy/com/gorylenko/SLF4JBindingPostShadowTest.groovy
To prevent the plugin from shipping its own slf4j-api jar,
which is improperly relocated and hence fails to bind to the gradle
provided sfl4j implementation, this commit excludes the slf4j-api from
grgit.
The commit additionally contains an integration test that tests the
shadowed plugin jar to ensure slf4j can properly bind.
Resolves: #203
> Exclude slf4j-api from grgit

- src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy
- src/test/groovy/com/gorylenko/MultiProjectGitDirectoryFunctionalTest.groovy
- Restore automatic .git directory detection that walks up project hierarchy
- Add findGitDirectory() method to locate .git in parent projects
- Maintains backward compatibility and configuration cache support
- Add comprehensive functional tests for multi-project scenarios
Resolves: https://github.com/n0mer/gradle-git-properties/issues/240
> Fix multi-project .git directory resolution (issue #240)
